[package]
name = "parui"
description = "Simple TUI frontend for paru or yay."
version = "1.0.3"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Vonr/parui"
repository = "https://github.com/Vonr/parui"
keywords = ["tui", "terminal", "frontend", "paru"]
include = ["src/**/*", "README.md"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = 0
strip = "symbols"

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false

[dependencies]
crossterm = "0.26.0"
tui = { version = "0.19", features = ["crossterm"] }
tokio = { version = "1.25.0", features = ["process", "rt-multi-thread", "time", "macros", "sync"] }
atomic = "0.5.1"
parking_lot = "0.12.1"
nohash-hasher = "0.2.0"
ureq = "2.6.2"
