[package]
name = "parui"
description = "Simple TUI frontend for paru or yay."
version = "1.0.8"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Vonr/parui"
repository = "https://github.com/Vonr/parui"
keywords = ["tui", "terminal", "frontend", "paru"]
include = ["src/**/*", "README.md"]
rust-version = "1.68.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = 0
strip = "symbols"

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false

[dependencies]
atomic = "0.5.3"
parking_lot = "0.12.1"
nohash-hasher = "0.2.0"
compact_strings = "1.2.2"
dhat = "0.3.2"

[dependencies.crossterm]
version = "0.26.1"
default-features = false

[dependencies.tokio]
version = "1.28.2"
features = ["process", "rt-multi-thread", "time", "macros", "sync"]

[dependencies.tui]
package = "ratatui"
version = "0.21.0"
features = ["crossterm"]

[dependencies.ureq]
version = "2.6.2"
default-features = false
features = ["gzip", "tls", "native-tls"]

[features]
dhat = []
